### ISSUE TITLE
feature request: export a model from a machine

### ISSUE THREAD

**Issue by horacioh** [statelyai/editor-feedback#1]
As a State machine addict (or user), I want to export models from all the systems I build with the editor, so I can send events using the model (type safety, and keep building systems the way I do it right now)

**Comment by mattpocock** [comment]
I think this might only have limited usefulness, because it wouldn't _sync_ to the previous model you'd created. I.e. if you'd said that event of type `CHANGE` needed a `value: string` attribute, you'd need to sync that manually to the new model you exported.

**Comment by horacioh** [comment]
I guess you can export both the model and the machine object? Not sure how many people use models to create machines tho..

**Comment by davidkpiano** [comment]
Since we are deprecating `createModel`, this feature will probably not happen. However, we will keep the idea of exporting types in mind.
