### ISSUE TITLE
Bug: "Mark As Initial State" menu option on Parallel states

### ISSUE THREAD

**Issue by brunocrosier** [statelyai/editor-feedback#100]
![image](https://user-images.githubusercontent.com/18399089/169648852-66a24e48-1ecc-48c0-82b3-71c9be632336.png)

When you right-click a parallel state, the menu shows an option to "Mark As Initial State", but I think this shouldn't be available as an option in this case

**Comment by Andarist** [comment]
To clarify - you mean a direct child state of a parallel state, right?

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1483/parallel-regions-should-not-be-markable-as-initial-states

**Comment by mattpocock** [comment]
Added PR to private repo

**Comment by mattpocock** [comment]
Sent to prod
