### ISSUE TITLE
Login not working for me

### ISSUE THREAD

**Issue by etangreal** [statelyai/editor-feedback#102]
Hi, 

So somehow my login auth via via github doesn't work - other people don't seem to have this problem (there doesn't seem to be an open issue). Nothing is wrong in my network tab (dev tools) every request is going through just fine, but when it's done the "Sign In" button is there and trying again results in exactly the same...

Any ideas?

**Comment by etangreal** [comment]
In the browser

**Comment by etangreal** [comment]
![chrome-version](https://user-images.githubusercontent.com/144399/170544420-e9033bcc-aa0c-4cb8-86f7-fec6b0832abc.png)
![ubuntu-version](https://user-images.githubusercontent.com/144399/170544425-94467f8e-94b8-49cb-8f06-eff45f0af3af.png)
![vscode-error](https://user-images.githubusercontent.com/144399/170544428-0636df40-686b-4e22-8a8e-9846a84523d3.png)
![vscode-version](https://user-images.githubusercontent.com/144399/170544430-bf21285d-34f7-4750-8f57-7cf9663f6d6f.png)

**Comment by etangreal** [comment]
the XState plugin is installed in vscode but gives the above error when i try to open xstate, or try to sign in

**Comment by etangreal** [comment]
![chrome-dev-tools](https://user-images.githubusercontent.com/144399/170547508-e4db99c4-441b-44ce-b8aa-5e4ce013ef2a.png)

**Comment by etangreal** [comment]
This (see chrome + dev tools in previous comment) is after a login attempt

**Comment by etangreal** [comment]
tried this in firefox ... same issue
![stately ai-firefox](https://user-images.githubusercontent.com/144399/170834286-3e9f5ff1-b10a-45ff-b9e8-1a72877316fc.png)

**Comment by davidkpiano** [comment]
The likely reason for this is a recent Supabase outage: https://status.supabase.com/

**Comment by davidkpiano** [comment]
@etangreal Did the problem resolve?

**Comment by etangreal** [comment]
i tired this again, this time on a macbook - still the same issue ... i'm guessing this has something to do with the specific setup of my github account (since no one else seems to have this issue), although what I couldn't say for sure - settings look pretty standard, have 2FA enabled. Think the next step might be to just register a new github account and try using it to login.

**Comment by mellson** [comment]
@etangreal let me know if you were able to resolve this? If not have you checked that your [email is verified](https://docs.github.com/en/get-started/signing-up-for-github/verifying-your-email-address) with GitHub?

**Comment by etangreal** [comment]
Yeah that did it ... turns out i had 2 email addresses - the second one was the primary and also unverified.
Thanks!

**Comment by mellson** [comment]
> Yeah that did it ... turns out i had 2 email addresses - the second one was the primary and also unverified. Thanks!

Happy that you managed to get in, and thanks for letting us know!
