### ISSUE TITLE
Multiple onDone transitions are shown as errors in the sidebar

### ISSUE THREAD

**Issue by tivac** [statelyai/editor-feedback#13]
Trying to recreate this simple machine in the editor:

https://stately.ai/viz/cdf792f7-5853-434a-af33-88cff000d4a0

![image](https://user-images.githubusercontent.com/49545/150855356-53add1e3-d989-4dbf-8c84-a88ec48a556a.png)

But when I recreate it in the editor it yells at me about having multiple `onDone` transitions with the same source, even though that's totally fine in Xstate.

https://stately.ai/registry/editor/3dfcae4d-8aea-4e2c-9cc2-ef0779b760df

![image](https://user-images.githubusercontent.com/49545/150855526-0be891da-142a-40ef-bffb-6563c7052301.png)

**Comment by mattpocock** [comment]
@tivac The issue with defining multiple events in the editor is that you don't know the intended _execution order_ of those events. This is even an issue in the viz itself - we don't show _in which order_ the conds are processed.

**Comment by mattpocock** [comment]
What you're trying to do in the editor is essentially:

```ts
on: {
  'state.done': {},
  'state.done': {},
}
```

Whereas what you should do is add an ELSE transition to the first onDone:

```ts
on: {
  'state.done': [{}, {}]
}
```

**Comment by mattpocock** [comment]
Actually, will keep this open as there might be more that we can do to make this clearer

**Comment by tivac** [comment]
> Whereas what you should do is add an ELSE transition to the first onDone:

Looking at the original source code in the visualizer, that's what I have.

```
onDone: [
    {
        target: "finishOne",
        cond: () => false,
    },
    {
        target: "finishTwo"
    }
],
```

But I don't see a way to define that in the editor aside from clicking and dragging multiple times from the source node, which it then yells at me about?

**Comment by mattpocock** [comment]
@tivac What you want to do is add multiple guards to the first onDone you created:

![image](https://user-images.githubusercontent.com/28293365/150857448-38fc16ce-20c9-4c43-8033-86b512eeebc9.png)

**Comment by tivac** [comment]
@mattpocock oh, I kept looking in the sidebar for how to do it.

For anybody else who gets stuck on this and comes along later, you need to do this:

![image](https://user-images.githubusercontent.com/49545/150866463-43a7a310-5bcd-4669-adca-2a4206536d09.png)

🤦🏻‍♂️
