### ISSUE TITLE
Bug: VSC extension opens editor in dark mode only

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#147]
### Description

Opening a machine using the VSC extension will render the editor with the dark theme, regardless of OS theme (when using auto) or manually setting light theme in the VSC extension settings.

### Expected result

Open editor with light theme when OS or extension configured for light theme.

### Actual result

Opens editor with dark theme.

### Additional details

https://user-images.githubusercontent.com/12085950/208947366-d3c03efe-a0de-4e1a-89ea-971834df7c86.mp4

**Comment by mellson** [comment]
The fix is rolling out now with [v1.11.3](https://github.com/statelyai/xstate-tools/releases/tag/stately-vscode%401.11.3). Thanks for reporting this.
