### ISSUE TITLE
Switching to Simulate mode causes crash for a specific statechart

### ISSUE THREAD

**Issue by aceslick911** [statelyai/editor-feedback#162]
---
Studio version: 0.46.1

```
_app-8968e77654567c4b.js:11 Error: Invalid transition definition for state node '[redacted].[redacted].[redacted].[redacted].[redacted].[redacted]':
Child state 'REQ' does not exist on '[redacted].[redacted].[redacted].[redacted].[redacted]'
```

Please message me on discord: aceslick911 and I'll be happy to share a unlisted link to the model

**Comment by aceslick911** [comment]
Ok so I just noticed that there were two child states with the exact same name - this is probably what contributed / caused the crash 😅 

Only one of these duplicate states had a child state called "REQ" which was being targeted by a transition

**Comment by davidkpiano** [comment]
Thanks for identifying the cause. We should ensure that only valid statecharts can be simulated.
