### ISSUE TITLE
laggy

### ISSUE THREAD

**Issue by alita-moore** [statelyai/editor-feedback#164]
This might be a small thing, but I'm having performance issues. In particular, when working with larger machines. For example (if you have access to my account), auth manager is quite slow on my browser (firefox).
---
Studio version: 0.47.3

**Comment by davidkpiano** [comment]
Thanks for the report, Alita. We will be investigating performance issues this week (releasing some UI updates).

Can you provide more details in where you're seeing performance issues? E.g. dragging, panning, adding states/transitions, etc.?

**Comment by alita-moore** [comment]
I'm seeing it just about everywhere, mostly around panning and dragging, though. It starts to make larger machines more difficult due to the difficulty in dragging / panning. But it's not a deal breaker. Thanks!

**Comment by mellson** [comment]
@alita-moore thanks for the report - we've recently released a few performance upgrades to the Studio. So I'm hoping the editor is less laggy now?
