### ISSUE TITLE
Bug: null context string exported as "null" string.

### ISSUE THREAD

**Issue by natedx** [statelyai/editor-feedback#167]
### Description

Create a context key-value pair where the value is a string, and toggle the "set initial value to null" option.
Go to the "code" export tab : the created context doesn't contain the `null` value but the non-empty "null" string. 

### Expected result

The output I expected is : 
```
{
...
  context: {
      yourStringContext: null,
    },
...
}
```
This behavior is correct for other types (number, boolean, object ...)

### Actual result

The value is a string containing "null", instead of the `null` value.
```
{
...
  context: 
      yourStringContext: "null",
    },
...
}
```

### Which browsers are you seeing the problem on?

Firefox

**Comment by davidkpiano** [comment]
This should no longer occur (make sure to set the type to **Auto**)

<img width="472" alt="CleanShot 2023-11-13 at 20 31 27@2x" src="https://github.com/statelyai/studio-issues/assets/1093738/f1b04fc9-67d1-49e6-b8c4-9b3a95e68e62">
