### ISSUE TITLE
Meta properties not populated correctly

### ISSUE THREAD

**Issue by sam-lippert** [statelyai/editor-feedback#170]
![image](https://github.com/statelyai/studio-issues/assets/837697/54275e55-835b-4213-83be-e6d6fd750446)

This should show the string or object value. The code still contains the meta value, but it is not being displayed. 
---
Studio version: 0.48.0

**Comment by farskid** [comment]
@sam-lippert Thanks for your feedback! I think this is due to the recent Studio release and a missing migration for meta values. We'll get to fixing it very soon.

**Comment by farskid** [comment]
@sam-lippert Could you double-check this issue, please? We've released a few patches that would fix this particular issue.

**Comment by sam-lippert** [comment]
I am having difficulty verifying this because my machine definitions are no longer accepted for import with the error message `Failed to parse machine definition`. Did the meta object format change? For some meta objects, I want to store strings, but for others, I want to store objects. The editor only seems to be allowing strings now.

**Comment by sam-lippert** [comment]
@farskid I see that the machine import parsing has been fixed, and I am able to set and see meta properties and export the machine, but I am still unable to import a state machine with meta properties. Should I open a new ticket for this?

**Comment by davidkpiano** [comment]
> @farskid I see that the machine import parsing has been fixed, and I am able to set and see meta properties and export the machine, but I am still unable to import a state machine with meta properties. Should I open a new ticket for this?

Yes please!
