### ISSUE TITLE
Help menu renders under the main panel controls

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#172]
![image](https://github.com/statelyai/studio-issues/assets/12085950/85f07671-596b-4e0c-98c2-197e36ed05e6)

---
Studio version: 0.48.0

**Comment by kevinmaes** [comment]
Thanks for reporting this issue @Valkendorm ! We have a fix and will release it soon.

**Comment by davidkpiano** [comment]
All fixed!

![CleanShot 2023-07-10 at 16 14 28](https://github.com/statelyai/studio-issues/assets/1093738/7887cbfa-db10-4ed3-9fd5-c5404bd7dc61)
