### ISSUE TITLE
import does not work for exported code as xstate v5 beta

### ISSUE THREAD

**Issue by zhanglongqi** [statelyai/editor-feedback#173]
---
Studio version: 0.48.3

**Comment by davidkpiano** [comment]
Can you please explain this issue a bit more?

**Comment by zhanglongqi** [comment]
the code exported as v5 beta can not be imported back.

**Comment by zhanglongqi** [comment]
Am I clear? do you need more info? @davidkpiano

**Comment by davidkpiano** [comment]
> Am I clear? do you need more info? @davidkpiano

Yes. Importing v5 beta is experimental (because v5 is still in beta) but we are working on it.
