### ISSUE TITLE
Assignments using expressions don't seem to work

### ISSUE THREAD

**Issue by abrgr** [statelyai/editor-feedback#176]
When creating an assignment action, setting the value type to "expression" (instead of "value") and using an expression like `true` or `(true)`, once I export the code the assignment is exported as the string "true" instead of the boolean expression `true`.

---
Studio version: 0.54.1

**Comment by davidkpiano** [comment]
Thanks for the report. We will be simplifying how assign and context works soon (in fact, just merged a related PR!)

**Comment by abrgr** [comment]
Oops. This report is erroneous. I understand now that the expression is a function. `() => true` works. It was just surprising to me that `true` as an expression was converted to a string value.

Excited to try out the simplified assign & context!

**Comment by davidkpiano** [comment]
Awesome; I'll go ahead and close it. Thanks for double-checking!

**Comment by abrgr** [comment]
The change you pushed out for assignment actions today is awesome. Thanks!
