### ISSUE TITLE
Renaming a machine from the sidenav won't keep the new name on the machine

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#177]
https://github.com/statelyai/studio-issues/assets/12085950/194942eb-b02d-4337-84fe-e2f7e1c7f8fc

---
Studio version: 0.55.0

**Comment by davidkpiano** [comment]
Thanks for the report; we're fixing this regression.

**Comment by mellson** [comment]
Hi @Valkendorm 👋 

Sorry about the inconvenience, and thanks for reporting the error! It should be working again now. Have a great weekend.
