### ISSUE TITLE
Bug: Export code for XState v4 is with syntax for XState v5

### ISSUE THREAD

**Issue by Osky772** [statelyai/editor-feedback#178]
---
Studio version: 0.56.0

When I export machine code for XState v4, it generates code like its XState v5
```
target: "Initial state",
            actions: {
              type: "reset",
              params: {},
            },
```
but this actions syntax is for XState v5 and it doesnt work in XState v4 right?

**Comment by davidkpiano** [comment]
You're correct, although in practice `params: { ... }` works for both v4 and v5, and it is recommended to place action params inside the `params` object.

**Comment by davidkpiano** [comment]
This is now fixed.
