### ISSUE TITLE
Bug: Error 500 in new version - Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by alapeta** [statelyai/editor-feedback#179]
### Description

After latest Stately Studio update all my machines are no longer displayed in editor. They produce Error 500 - Cannot read properties of null (reading 'type').
The last time when I saw them working was around Jul 16th.

<img width="1060" alt="Zrzut ekranu 2023-08-6 o 12 37 32" src="https://github.com/statelyai/studio-issues/assets/52104083/dd6584dc-c03e-4db8-b3ba-414dd74b6ee3">

Creating a new machine and trying to import these machines from JSON - fails with no explanations...

### Expected result

Current machines versions kept in Stately register should always work after update of editor...

### Actual result

New version od Stately is incompatible with machines created in it just few days ago.
There is no warning, no explanation, no clue - what to do.

### Which browsers are you seeing the problem on?

Chrome, Safari

### Additional details

share link to machine is:
https://stately.ai/registry/editor/6519edfe-f874-42ec-b6e6-be2bd7809c3d

full machine json is below:

{
    "id": "Auth",
    "predictableActionArguments": true,
    "preserveActionOrder": true,
    "context": {
        "token": null,
        "user": null
    },
    "description": "Application Auth behavior.",
    "meta": {
        "mall": null,
        "uid": null
    },
    "initial": "Init",
    "states": {
        "Init": {
            "description": "Auth starting point.",
            "exit": {
                "params": {},
                "type": "bindMallData"
            },
            "invoke": {
                "src": "appInit",
                "id": "appInit",
                "onDone": [
                    {
                        "target": "Logging via token",
                        "cond": "token"
                    },
                    {
                        "target": "Getting current logged user"
                    }
                ],
                "onError": [
                    {
                        "target": "Init failed"
                    }
                ]
            }
        },
        "Logging via token": {
            "invoke": {
                "src": "loginWithToken",
                "onDone": [
                    {
                        "target": "Getting current logged user"
                    }
                ],
                "onError": [
                    {
                        "target": "Getting current logged user"
                    }
                ]
            }
        },
        "Getting current logged user": {
            "exit": {
                "assignment": {
                    "type": "object",
                    "value": {
                        "user": {
                            "type": "string",
                            "value": "(context, event)=>event.data.user"
                        }
                    }
                },
                "type": "xstate.assign"
            },
            "invoke": {
                "src": "getAuthState",
                "id": "getAuthState",
                "onDone": [
                    {
                        "target": "Logged in User",
                        "cond": "user"
                    },
                    {
                        "target": "Creating anonymous User",
                        "description": "If there is no user - create new one"
                    }
                ]
            }
        },
        "Logged in User": {
            "description": "Firebase Auth User is logged",
            "exit": {
                "params": {},
                "type": "bindUserData"
            },
            "invoke": {
                "src": "bindProfile",
                "id": "bindProfile",
                "onError": [
                    {
                        "target": "Creating new empty Profile"
                    }
                ],
                "onDone": [
                    {
                        "target": "Anonymous",
                        "cond": "isAnonymous"
                    },
                    {
                        "target": "Member"
                    }
                ]
            }
        },
        "Creating anonymous User": {
            "invoke": {
                "src": "signUpAnonymous",
                "onDone": [
                    {
                        "target": "Getting current logged user"
                    }
                ]
            }
        },
        "Creating new empty Profile": {
            "invoke": {
                "src": "createProfile",
                "onDone": [
                    {
                        "target": "Logged in User"
                    }
                ]
            }
        },
        "Anonymous": {
            "description": "User is logged as anonymous. Provide prompts for login/signup",
            "entry": {
                "params": {},
                "type": "registrationPrompt"
            },
            "on": {
                "SIGNUP": {
                    "target": "Signing Up"
                },
                "LOGIN": {
                    "target": "Logging In"
                }
            }
        },
        "Member": {
            "description": "Registered Member has logged.",
            "entry": {
                "params": {},
                "type": "helloMember"
            },
            "on": {
                "LOGOUT": {
                    "target": "Logging Out"
                }
            }
        },
        "Signing Up": {
            "invoke": {
                "src": "signUp",
                "id": "signUp",
                "onDone": [
                    {
                        "target": "Getting current logged user"
                    }
                ],
                "onError": [
                    {
                        "target": "Anonymous"
                    }
                ]
            }
        },
        "Logging In": {
            "invoke": {
                "src": "signIn",
                "id": "logIn",
                "onDone": [
                    {
                        "target": "Getting current logged user"
                    }
                ],
                "onError": [
                    {
                        "target": "Anonymous"
                    }
                ]
            }
        },
        "Logging Out": {
            "invoke": {
                "src": "logOut",
                "id": "logOut",
                "onDone": [
                    {
                        "target": "Getting current logged user",
                        "actions": {
                            "params": {},
                            "type": "cleardata"
                        }
                    }
                ],
                "onError": [
                    {
                        "target": "Member"
                    }
                ]
            }
        },
        "Init failed": {
            "description": "App init failed - mall is not loaded",
            "entry": {
                "params": {},
                "type": "initFailed"
            },
            "type": "final"
        }
    }
}

**Comment by davidkpiano** [comment]
Looking into this now.

**Comment by davidkpiano** [comment]
This is now working ✅
