### ISSUE TITLE
Bug: An always transition with if/else does not transition in the simulator

### ISSUE THREAD

**Issue by islami00** [statelyai/editor-feedback#181]
### Description

An always transition with if/else does not transition in the simulator [Machine](https://stately.ai/registry/editor/b704d410-fb0f-48c3-bdce-3297726568c4?machineId=59bf4783-93c8-441b-a0bb-86d9910b08c6&mode=Simulate)

### Expected result

I should be able to select which of the conditions evaluates to true 

### Actual result

I cannot select either of the transitions

### Which browsers are you seeing the problem on?

Chrome

### Additional details

Initial thread on discord: https://discord.com/channels/795785288994652170/1133461605150097409/1133485223238172864

**Comment by davidkpiano** [comment]
This will be fixed soon, thanks for pointing it out.

**Comment by davidkpiano** [comment]
This is now working.

https://github.com/statelyai/studio-issues/assets/1093738/de035939-78a5-4b59-9b8d-7dd5292a2513

**Comment by bentron2000** [comment]
I think this may still be an issue - [see complex modal example here](https://stately.ai/registry/editor/d705442c-3cbb-456c-82cf-5634b857ddbb?machineId=9487e44e-e761-4097-ace6-f2a779a2dfe9&mode=Simulate)
