### ISSUE TITLE
Bug: simulating lowercase "exit" transitions

### ISSUE THREAD

**Issue by abooayoob** [statelyai/editor-feedback#183]
---
Studio version: 0.61.3

Can't simulate transitions named "exit" with a lower case.

[Link to Machine](https://stately.ai/registry/editor/42482b89-d23a-4c8c-8f52-27d9d1dfd163?machineId=ec5dd750-a6f4-4487-a197-d03b2086f57b&mode)

https://github.com/statelyai/studio-issues/assets/9134348/c0e9a7d4-66b3-4349-ae61-f10891a91ed2

**Comment by davidkpiano** [comment]
We've identified the cause and are fixing it soon. cc. @farskid

**Comment by davidkpiano** [comment]
This has now been fixed.

https://github.com/statelyai/studio-issues/assets/1093738/935d650f-1cfe-4156-a5af-8a335a144d57

**Comment by abooayoob** [comment]
Nice, thanks!
