### ISSUE TITLE
I can't delete machines from my project, the toast show that "an unknown error occured"

### ISSUE THREAD

**Issue by Osky772** [statelyai/editor-feedback#184]
---
Studio version: 0.61.4

our login: admin@edrone.me

**Comment by mellson** [comment]
@Osky772 Thank you for the info. We're currently having a small problem with some serverless functions. Should be fixed soon 🤞🏻

**Comment by mellson** [comment]
@Osky772 deleting machines should work again. We're still fixing an underlying issue, so creating image URLs for machines is currently not working (should be fixed soon).
