### ISSUE TITLE
Live Simulation does not work

### ISSUE THREAD

**Issue by inverted-capital** [statelyai/editor-feedback#187]
### Description

We purchased two pro seats to use the live simulation feature, and whilst comparing screens using video screen sharing, and confirming that both sides reported "joining live simulation" with the same codes, neither of us could see the transitions being taken by the other side using stately.ai alone.

We tried Opera and Chrome, and the usual combination of refreshes, restarts, and prayer.

Please can someone fix this ?

### Expected result

Feature should work as advertised - a "live simulation"

### Actual result

we got a dead simulation.

### Which browsers are you seeing the problem on?

Chrome

**Comment by davidkpiano** [comment]
Thanks for the report. We are looking into this now.

**Comment by mellson** [comment]
@inverted-capital should work now; sorry for the inconvenience. Can you check if it works on your end?

**Comment by inverted-capital** [comment]
Works perfectly - thank you.  FYI this has not been working for the last 24 hours at least.

**Comment by mellson** [comment]
> Works perfectly - thank you.  FYI this has not been working for the last 24 hours at least.

Thank you for the reply! Happy to hear it's working again. It was a manual error on my end, I forgot to hit the deploy button for our live sim mode backend 🤦‍♂️ We're automating the deployment so it won't happen again.
