### ISSUE TITLE
Import and Export bugs

### ISSUE THREAD

**Issue by ivanant** [statelyai/editor-feedback#190]
Hi,
1, Export and choose JSON format. "Actions" are missed.
2, Fail to Import with JSON format. It shows "Failed to parse machine definition". JS format is ok.

---
Studio version: 0.73.0

**Comment by farskid** [comment]
Hi @ivanant and thanks for reporting this.
Could you please share the machine you're having problems with?
Currently, we omit actions with inline implementations from the JSON export if that's what's missing in your case :)

**Comment by ivanant** [comment]
Hi,
Please check these:
![image](https://github.com/statelyai/studio-issues/assets/2087057/e4ccd447-10ba-47b6-b03b-e0e9d9f51963)
JSON format (wrong):
![image](https://github.com/statelyai/studio-issues/assets/2087057/68b5e2b6-4698-4f48-b3f6-b11dcfae7ef4)
JS format (correct):
![image](https://github.com/statelyai/studio-issues/assets/2087057/4e124ef1-7f4e-4b85-84e6-d14ef6ce1e30)

**Comment by davidkpiano** [comment]
@ivanant Thanks for this, we'll fix this soon.

**Comment by farskid** [comment]
> Hi, Please check these: ![image](https://user-images.githubusercontent.com/2087057/268450601-e4ccd447-10ba-47b6-b03b-e0e9d9f51963.png) JSON format (wrong): ![image](https://user-images.githubusercontent.com/2087057/268450712-68b5e2b6-4698-4f48-b3f6-b11dcfae7ef4.png) JS format (correct): ![image](https://user-images.githubusercontent.com/2087057/268450822-4e124ef1-7f4e-4b85-84e6-d14ef6ce1e30.png)

This is already fixed and will be released soon :)

**Comment by ivanant** [comment]
I still can not import JSON format.  
I found a new bug after your latest release.
All actions are missing after importing from the js format.
![image](https://github.com/statelyai/studio-issues/assets/2087057/ede64c18-c76d-4ee2-9c99-4797c18a12cc)

**Comment by farskid** [comment]
> I still can not import JSON format. I found a new bug after your latest release. All actions are missing after importing from the js format. ![image](https://user-images.githubusercontent.com/2087057/268506792-ede64c18-c76d-4ee2-9c99-4797c18a12cc.png)

Can you please share the JS code you're importing? Can you try again also? There's a chance you might've imported before the release happened.

**Comment by ivanant** [comment]
I can import JS and export JSON now.
However, I still can not import JSON that is exported from the system.
![image](https://github.com/statelyai/studio-issues/assets/2087057/3f483a5e-1951-4b06-8354-deaa61fdc319)

**Comment by farskid** [comment]
> I can import JS and export JSON now.
> 
> However, I still can not import JSON that is exported from the system.
> 
> ![image](https://github.com/statelyai/studio-issues/assets/2087057/3f483a5e-1951-4b06-8354-deaa61fdc319)
> 
> 

That seems to be separate issue that I'm trying to fix as we speak.

**Comment by ivanant** [comment]
Thanks. All bugs are fixed.

**Comment by farskid** [comment]
> Thanks. All bugs are fixed.

Amazing! Glad bug fixes are working for you. Thanks for reporting again :)
