### ISSUE TITLE
Bug: unable to consult my projects

### ISSUE THREAD

**Issue by gabrielvv** [statelyai/editor-feedback#191]
### Description

When trying to consult any of my project:

![Capture d’écran du 2023-09-15 14-30-03](https://github.com/statelyai/studio-issues/assets/13749457/f87870db-6531-4d39-b8c2-8340c3c97fdd)

I am logged in with a github account

### Expected result

I would like to be able to edit / display my projects. 

### Actual result

![Capture d’écran du 2023-09-15 14-30-03](https://github.com/statelyai/studio-issues/assets/13749457/f87870db-6531-4d39-b8c2-8340c3c97fdd)

### Which browsers are you seeing the problem on?

Firefox

**Comment by mellson** [comment]
@gabrielvv thanks for the report; I'll look into this now and get back asap.

**Comment by mellson** [comment]
Hi @gabrielvv, which version of firefox are you on? Is it possible for you to update to the latest version and retry?

**Comment by gabrielvv** [comment]
I use Firefox v110.0.1 (on Ubuntu) and chromium.
It works on chromium so I can consult my projects.
Thanks !

**Comment by mellson** [comment]
> I use Firefox v110.0.1 on Ubuntu and chromium and it works on chromium.

Thank you for the reply. Are you able to update to the latest Firefox on Ubuntu? It should work from v115 and up

**Comment by gabrielvv** [comment]
I updated Firefox (117.0.1) and it works

**Comment by mellson** [comment]
> I updated Firefox (117.0.1) and it works

Thanks for the reply, happy to hear that updating worked. Have a great weekend!
