### ISSUE TITLE
Bug: Editing Context Schema

### ISSUE THREAD

**Issue by tyler-morrison** [statelyai/editor-feedback#197]
### Description

The form validation on the "Property Name" field prevents schema edits after initial creation.

<img width="1552" alt="Stately-Editor-Context-Bug" src="https://github.com/statelyai/studio-issues/assets/8642365/2be41fbf-5658-4e7f-a9d2-f510ee2d9b61">

## Scenario:
I created a new "counter" property on the schema, but accidentally selected the wrong property type.

## Steps to Reproduce:
1. Open the "Context Schema" panel
2. Click the "+" button to create a new property named `counter`
3. Click "Create property" to save changes
4. Click the "counter" property to open the edit property modal
5. Attempt to change "Property type" field from `String` to `number`
6. Attempt to add a "Description" to the property

### Expected result

The property type / description should be editable.

### Actual result

The "Property Name" field displays an error…
> _Provide a unique context property name_

… and changes cannot be saved because the form is invalid.

### Which browsers are you seeing the problem on?

Firefox

**Comment by farskid** [comment]
@tyler-morrison This bug is fixed and available on latest Studio 🙂
