### ISSUE TITLE
"Color" choice on dropdown menu is locked on Pro account

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#198]
Opening the right-click dropdown on a node will show a "Color" option, which appears as locked even on a Pro account.

![image](https://github.com/statelyai/studio-issues/assets/12085950/5382e29b-368d-47d0-9d7e-730c2c64abcf)

Trying to use this option will bring the following dialog.

![image](https://github.com/statelyai/studio-issues/assets/12085950/1b3a026d-7f82-464a-ac7b-3c207009c263)

---
Studio version: 0.85.7

**Comment by Valkendorm** [comment]
Please disregard this. I just realized this page was running on the old UI. I refreshed the page and all is good.

![image](https://github.com/statelyai/studio-issues/assets/12085950/df344395-51a4-4dfb-a2e7-3ab0a5e35397)

**Comment by kevinmaes** [comment]
@Valkendorm I'm glad that was the only issue and that everything is ok now!
