### ISSUE TITLE
Dark mode is not persisted

### ISSUE THREAD

**Issue by florian-lefebvre** [statelyai/editor-feedback#201]
Each time I restart my browser, studio is in light mode even though I did set dark mode
---
Studio version: 0.90.0

**Comment by kevinmaes** [comment]
Sorry for the inconvenience this has caused you; is it still happening for you now? We are looking into the issue. In the meantime, could you please provide me with more information regarding your browser, version, etc. Have you noticed this also happening if you were to try it in a different browser from the one you normally use? Thanks in advance for helping us to pinpoint the problem.

**Comment by florian-lefebvre** [comment]
Looks like it's now persisted so no worries!

**Comment by kevinmaes** [comment]
Very happy to hear that and thanks for reporting it and for confirming that it works so quickly! Let us know if you have any further issues with that!
