### ISSUE TITLE
cannot access Help->Tutorials

### ISSUE THREAD

**Issue by reliablecontrols** [statelyai/editor-feedback#202]
---
Studio version: 0.90.1
context: logged in as non-pro -user

GIVEN I select 
![image](https://github.com/statelyai/studio-issues/assets/105379045/e64b8345-efee-4900-8bd1-dcee218fc34e)
Help->Tutorials
the link does not open anything.

**Comment by davebneufeld** [comment]
signing in on my other account 2023-11-05. Looks like it works now.
![image](https://github.com/statelyai/studio-issues/assets/17053403/b43ad6c4-0775-44fd-91de-26d51e309591)

Issue can be closed. Thanks.
