### ISSUE TITLE
Inline guards are lost after importing machine into Studio

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#204]
Importing a machine that has an inline guard will lose the guard once imported.

It can be reproduced using this sample :

```js
createMachine({
  id: "machine",
  on: {
    event: {
      guard: ({ context, event }) => false,
    }
  }
});
```

Once imported in the Studio, the guard won't be here :

![image](https://github.com/statelyai/studio-issues/assets/12085950/6eff19fc-1030-4bae-b9a8-c8fa268c6358)

The code preview gives the following :

```js
import { createMachine } from "xstate";

export const machine = createMachine(
  {
    id: "machine",
    on: {
      event: {
        target: "#machine",
      },
    },
    types: { events: {} as { type: "event" } },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  },
);
```

---
Studio version: 0.92.3

**Comment by davidkpiano** [comment]
Thanks for reporting this. We have a good idea on how to fix this (and importing support for v5 in general), and will keep you updated.

**Comment by Valkendorm** [comment]
Thanks. I have encountered other parts where it happened (event schema properties, for example). Do you want me to report them as well or they all fall into the same issue?

**Comment by davidkpiano** [comment]
This is now fixed - guards are now preserved (v4 and v5).
