### ISSUE TITLE
The "Save" button on state.new page uses white text in light mode

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#208]
Light mode.

![image](https://github.com/statelyai/studio-issues/assets/12085950/2ae20b56-e293-489d-b891-4dfa2ba5e876)

Looks fine in dark mode. 👍 

![image](https://github.com/statelyai/studio-issues/assets/12085950/3d02b940-b42f-41f4-93e0-a04f02fc8302)

---
Studio version: 0.97.4

**Comment by davidkpiano** [comment]
Thanks for the report. We have a few areas in this department to clean up.
