### ISSUE TITLE
Parallel states can't use onDone transition when all children are finished

### ISSUE THREAD

**Issue by tivac** [statelyai/editor-feedback#21]
This is a common pattern for us as a way to spray out a bunch of work in parallel, then wait for everything to finish and move on in the statechart.

![Visualizer representation of the pattern](https://user-images.githubusercontent.com/49545/150884837-155abb8b-4b58-44c2-a3b7-50ca659759f9.png)

<details>
  <summary>Pattern Details</summary>

https://stately.ai/viz/6ecac06f-7cc0-4031-8c07-eb3aa8233236

```js
import { createMachine } from 'xstate';

createMachine({
  initial: "parallel",
  id: "Visualizer",

  states:{ 
    parallel: {
      type: "parallel",

      states: {
        one: {
          initial: "child",

          states: {
            child: {
              on: {
                DONE: "done",
              },
            },

            done: { type: "final" }
          }
        },

        two: {
          initial: "child",

          states: {
            child: {
              on: {
                DONE: "done",
              },
            },

            done: { type: "final" }
          }
        },
      },

      onDone: "after",
    },
    after: {},
  },
});
```
</details>

Unfortunately, the editor doesn't seem to recognize that as a possibility.

https://user-images.githubusercontent.com/49545/150884988-18318531-1762-4d49-a951-56527e63307e.mp4

https://stately.ai/registry/editor/8fe422c4-35e8-408b-a227-455e9bdc351b

**Comment by mattpocock** [comment]
PR in progress for this

**Comment by mattpocock** [comment]
Merged, deploying live now
