### ISSUE TITLE
Generated code for a parallel machine will not run on CodeSandBox or StackBlitz

### ISSUE THREAD

**Issue by roundand** [statelyai/editor-feedback#211]
If I take my public [video player](https://stately.ai/registry/editor/272e421a-3473-4add-b87c-a45514882a83?machineId=578a4240-6c57-4256-b754-de764068ec82) and select "Export to Code", for either JavaScript or TypeScript, with a destination of either CodeSandBox or StackBlitz, I get an error:

[JavaScript/CodeSandBox] => [Type Error Cannot read properties of undefined (reading 'filter')](https://codesandbox.io/p/sandbox/interesting-rain-7zzp6v?file=%2Findex.html)
[JavaScript/StackBlitz] => "Error in /~/index.js (37:10) Cannot read properties of undefined (reading 'filter')"

[TypeScript/CodeSandBox] => [TypeError Cannot read properties of undefined (reading 'filter')](https://codesandbox.io/p/sandbox/white-sea-xn5x3x?file=%2Findex.html)
[TypeScript/StackBlitz] => "Error in /~/index.ts (37:10) Cannot read properties of undefined (reading 'filter')"

![image](https://github.com/statelyai/studio-issues/assets/1528635/c9ece556-da6f-4f24-9a18-4cae8943dcf8)

---
Studio version: 0.101.0

**Comment by davidkpiano** [comment]
Thank you for the report. We are working on fixing this now.

**Comment by kevinmaes** [comment]
Hi @roundand! the export feature should be fixed up now for StackBlitz and CodeSandbox for JS/TS and XState v4 and 5. Thanks for your patience!
