### ISSUE TITLE
Can't import from XState-Cataloge Form-Input example

### ISSUE THREAD

**Issue by tomByrer** [statelyai/editor-feedback#217]
Choked on this v4 TS example.  Not sure why & seemed to use up 2 of my 5 tokens to try, so giving up now.
https://xstate-catalogue.com/machines/form-input
---
Studio version: 0.111.4

**Comment by davidkpiano** [comment]
Looking into this; thank you for the report.

**Comment by davidkpiano** [comment]
Okay, this is our fault; I apologize. Currently we detect if a machine is an XState machine if there is `createMachine(` (note the parentheses); apparently this is not the best way since you're importing from TypeScript. Quick fix:

```diff
-const formInputMachine = createMachine<
- FormInputMachineContext,
- FormInputMachineEvent
->(
+const formInputMachine = createMachine(
```

**Comment by tomByrer** [comment]
Thanks for the fast research!

I hope you make Matt proud & add better TS support! ;)
(Though IMHO I can live perfectly fine without TS)
