### ISSUE TITLE
There was an error redirecting you to your Drafts project.

### ISSUE THREAD

**Issue by Uplink03** [statelyai/editor-feedback#220]
---
Studio version: 0.116.2

I just signed up. Brand new account. This is the first thing I see:

> There was an error redirecting you to your Drafts project.

Browser URL: https://stately.ai/registry/new?source=landing-page

I pressed the back button twice (going to before the signup/login screen) and then I was landed on a working editor.

Flow:
1. stately.ai homepage
2. Press "Try the visual editor"
3. See the login screen
4. Login with Github
5. Confirm permissions on Github
6. Error on stately.ai

**Comment by davidkpiano** [comment]
Thanks for the report. We will investigate and get this fixed ASAP.

**Comment by kevinmaes** [comment]
Hi @Uplink03 Thanks for reporting the issue. I was unable to reproduce this following the steps above. Does this ever happen again when trying to access the editor? It's possible that there was a momentary problem creating the project but let me know if you see this is still an issue. We'll definitely keep an eye out for it though.

**Comment by Uplink03** [comment]
@kevinmaes I highly doubt I'll ever see it again, but I reported my experience in the off chance that you have an "aha" moment - especially if it's a very rare occurrence and people don't report it because they just go back to the home page and things work fine.

**Comment by kevinmaes** [comment]
@Uplink03 This was helpful to us and we implemented a change we hope will prevent this from happening. Thanks again!
