### ISSUE TITLE
Issue with Adding Effects (Invoked Actor, Entry/Exit Actions) in Stately AI Studio

### ISSUE THREAD

**Issue by mbushpilot2b** [statelyai/editor-feedback#221]
## Description of the Issue:

I have encountered a problem within the Stately AI Studio web interface that affects the usability of adding effects to a state, specifically when dealing with Invoked Actor, Entry Action, and Exit Action. The main issues observed are as follows:

1. Invoked Actor: When attempting to create an "Effect" of type Invoked Actor, clicking the option does not trigger any action or response from the interface.
2. Entry/Exit Actions: Although I can create entry and exit actions, clicking on them afterward causes the state to become deselected instead of allowing for further interaction or modification.

Workaround Identified:

A temporary workaround I've found involves using the context menu that appears after clicking on a state. By selecting the option to invoke an actor, or choose entry/exit action from this menu, I am able to add the desired effects without encountering the issues mentioned above.

## Steps to Reproduce:

1. Navigate to the state configuration where you wish to add effects and click on it.
2. Click the Details button
3. Try to add an Invoked Actor effect by clicking on the respective option under the "Effects" – observe that nothing happens. or Try to add an entry or exit action from he "Effects" button and then click on the newly created action – notice that the state gets deselected.

### Expected Behavior:

- Clicking on the option to add an Invoked Actor should open the necessary interface or prompt to configure the invoked actor.
- After creating entry or exit actions, clicking on them should allow for editing or further configuration without deselecting the state.

### Actual Behavior:

- The interface does not respond when attempting to add an Invoked Actor.
- States become deselected when attempting to interact with newly created entry or exit actions.

### Video/Screencast:

I have captured a video demonstrating the issues described above:

https://github.com/statelyai/studio-issues/assets/4673917/084f5046-8c86-495b-bae4-9e77c9f45027

### Browser Version:

Chrome: Version 121.0.6167.184 (Official Build) (arm64)

### Operating System:

OSX Sonoma: 14.3.1 (23D60)

**Comment by farskid** [comment]
@mbushpilot2b Thanks for reporting this bug. I confirm I can reproduce it on latest production too. We'll work on a fix soon.

**Comment by mbushpilot2b** [comment]
Awesome Thanks!

**Comment by mbushpilot2b** [comment]
Thanks can confirm invoke actors effect works now. As for the entry and exit actions they disappear when clicked on in the input box still

**Comment by davidkpiano** [comment]
> Thanks can confirm invoke actors effect works now. As for the entry and exit actions they disappear when clicked on in the input box still

Can you open a separate issue for this?
