### ISSUE TITLE
Code-export for JavaScript XState v5 is broken

### ISSUE THREAD

**Issue by perbyhring** [statelyai/editor-feedback#222]
When i select **JavaScript** and **XState v5** in the code-tab, I get the same code as for TypeScript-export.
It includes type-declarations and breaks if I preview the project using the **Open in CodeSandbox**-link

Here's a simple test which illustrates the issue:
https://stately.ai/registry/editor/c2950326-2b62-491a-b97a-493a69d73018?machineId=ea7362b4-7033-4e77-9c63-b6ad326b93a4

---
Studio version: 0.118.2

**Comment by davidkpiano** [comment]
Thanks for the report; we'll investigate right away.

**Comment by kevinmaes** [comment]
@perbyhring Thanks for reporting this to us. We fixed this yesterday and I'm able to see the machine you shared here working in StackBlitz and CodeSandbox in both JS and TS. Let me know if you still experience any problem with this.
