### ISSUE TITLE
Bug: `fromPromise` is not imported from `"xstate"` on code generation

### ISSUE THREAD

**Issue by egorFiNE** [statelyai/editor-feedback#228]
### Description

Steps: 

1. Create an empty state machine with a single state.
2. Add an invocation of "invoke1" into a state.
3. Click on "<> Code" tab. Choose JavaScript and XState v5. 

### Expected result

```javascript
import { createMachine, fromPromise } from "xstate"; // Notice: fromPromise should be imported
export const machine = createMachine(
// ...
    actors: {
      invoke1: fromPromise({
        /* ... */
      })
// ...
``` 

### Actual result

```javascript
import { createMachine } from "xstate";
export const machine = createMachine(
// ...
    actors: {
      invoke1: fromPromise({
        /* ... */
      })
// ...
```

### Additional details

This is a trivial and minor bug that makes it impossible to blindly copy-paste the generated code into a file in project.

Also, code generation for TypeScript is a bit broken the same way, too.

**Comment by davidkpiano** [comment]
I can't quite reproduce this. Is this what you are doing?

https://github.com/statelyai/studio-issues/assets/1093738/36f13644-1ea8-4d13-b496-af88c59152b5

**Comment by egorFiNE** [comment]
Yeah my bad, I can't reproduce it. Seems like I messed up with export/import code or something so that there is a "fromPromise" in actual code, but there isn't a flag to add this function to imports.

I will reopen if I reproduce it cleanly.
