### ISSUE TITLE
Bug: [FIGMA] can't embed a design

### ISSUE THREAD

**Issue by giancarlosisasi** [statelyai/editor-feedback#233]
### Description

For some reason, the app always shows that the URL is invalid no matter what.

![image](https://github.com/statelyai/studio-issues/assets/17274950/15d9e623-37a3-431d-81b0-251864487f67)

### Expected result

Should not get an error when the url is valid.

### Actual result

![image](https://github.com/statelyai/studio-issues/assets/17274950/15d9e623-37a3-431d-81b0-251864487f67)

### Additional details

I have tested with other valid URLs used before in other projects and it still shows the error.
Maybe its related to a new release where the validation-url logic has changed?

**Comment by davidkpiano** [comment]
Thank you for the report. This will be fixed soon.

**Comment by davidkpiano** [comment]
We have just released a new version that should fix the issue. Please check in a few minutes, and feel free to reopen this if the issue persists.
