### ISSUE TITLE
Right-clicking state handle leaves phantom event transition

### ISSUE THREAD

**Issue by with-heart** [statelyai/editor-feedback#235]
When right-clicking a state handle, the editor displays a phantom event transition that can't be interacted with. Changing machines or refreshing the page removes the phantom.

![Screen capture demonstrating the editor leaving a phantom event transition](https://github.com/statelyai/studio-issues/assets/1954752/74cced73-ea2d-4c79-b2f6-493eb4a2007a)

---
Studio version: 0.123.4

**Comment by davidkpiano** [comment]
Fixed!
