### ISSUE TITLE
Tags are not added to the generated Typescript code

### ISSUE THREAD

**Issue by sbaechler** [statelyai/editor-feedback#242]
I can add tags to states in the visual editor, but they are missing from the generated Typescript code.

They are added to the generated Javascript code.

[Example project](https://stately.ai/registry/editor/aa900090-03ba-4f07-85ba-5520cc39a603?machineId=424d21e9-8d04-4c72-bb55-a85fa58918c3&mode=design)

---
Studio version: 0.125.0

**Comment by davidkpiano** [comment]
A fix has been made and will be live soon.

![CleanShot 2024-08-12 at 09 17 08](https://github.com/user-attachments/assets/edf6db3d-2176-4dae-8ceb-4a29c524bd51)

**Comment by sbaechler** [comment]
Wow, that was fast. Thank you.
