### ISSUE TITLE
[VSC extension] An open editor tab can overwrite other machines you have

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#26]
1. Open a machine in the editor and leave the tab open
2. Create a new machine (or open an existing one)
3. Click on the "Open Visual Editor" link from the machine (doesn't open a new tab, and is probably the source of the bug)
4. Click in the editor tab; the new machine's content is overwritten by the editor's content

After step 3 (left is new, center is current):
![image](https://user-images.githubusercontent.com/12085950/151172531-01381714-b753-49e8-b13d-3d23c57707d2.png)

After step 4 (editor's content is sent to left machine):
![image](https://user-images.githubusercontent.com/12085950/151172739-5782fcd3-f5fb-4c01-9759-0a04f7c17495.png)

**Comment by mattpocock** [comment]
@Valkendorm Fixed in 1.5.9
