### ISSUE TITLE
[VSC extension] Clicking Give Feedback option gives a blank page

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#30]
As seen from today's demo, clicking the "Give Feedback" option don't load the new issue url. :)

![image](https://user-images.githubusercontent.com/12085950/151563639-4bfadd0e-61c0-463f-a058-0b3c8311f89e.png)

**Comment by davidkpiano** [comment]
https://linear.app/statelyai/issue/STA-1127/clicking-give-feedback-option-gives-a-blank-page-in-vsc-extension

**Comment by mellson** [comment]
@Valkendorm thank you for reporting this. It should be fixed if you update to the latest version (1.8.2) of our VS Code extension.
