### ISSUE TITLE
[VSC extension] Simulate mode doesn't reset when the machine changes in VSCode

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#31]
Version: 1.5.6

It also seems to keep the Edit mode selection.

![image](https://user-images.githubusercontent.com/12085950/151572336-fd5c8aa6-6418-4c72-a11a-1fad24a4cd07.png)

```ts
const machine = createMachine({
  id: 'machine',
  initial: 'idle',
  states: {
    idle: {
      on: {
        LOAD: {
          target: '#machine.loading',
        },
      },
    },
    loading: {},
  },
});
```

**Comment by mattpocock** [comment]
Eh? Weird

**Comment by Valkendorm** [comment]
Ok, I see what's up now. It seems that the Simulate doesn't reset completely when the machine is modified in the code. So if you rename the state it was on, it gets lost.

**Comment by mattpocock** [comment]
Ahhhhh, that's a great catch.

**Comment by mattpocock** [comment]
Fixed, should be working now.
