### ISSUE TITLE
[VSC Extension] @xstate-layout comment is prepended to whatever is on line above createMachine

### ISSUE THREAD

**Issue by anton-g** [statelyai/editor-feedback#33]
When the createMachine call doesn't have an empty line above it (when it's wrapped in a factory function for example) the @xstate-layout comment is prepended to whatever is on that line. It should probably add a new line instead.

<img width="1042" alt="Screenshot 2022-01-29 at 11 13 48" src="https://user-images.githubusercontent.com/6201720/151657677-fbaf2b82-a31d-4985-bceb-dc843821e895.png">

**Comment by mattpocock** [comment]
Fixed in 1.5.8
