### ISSUE TITLE
Source of an invoke's onDone/onError events can be changed, which results in broken machines

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/editor-feedback#37]
When adding an invoke to a state and creating the `onDone/onError` events, it's possible to change the source of the even to another state (with or without invokes, as long as the invoke src has a different name). In the editor, the source will change to the selected state, but will be configured for an invoke that doesn't exist on it.

![image](https://user-images.githubusercontent.com/12085950/152406110-348fa3ea-5ca4-474d-9909-1c5890f0e81f.png)

### Exported machine

```json
{
  "id": "New Machine",
  "initial": "First State",
  "states": {
    "First State": {
      "invoke": {
        "src": "invokesomething"
      }
    },
    "new state 2": {
      "invoke": {
        "src": "invokeother"
      }
    },
    "new state 1": {}
  }
}
```

**Comment by mattpocock** [comment]
@Valkendorm Our plan for this is to have warnings which display on the canvas, which can be hovered for more info. This is a great one to point out.

**Comment by mattpocock** [comment]
Fixed in latest version
