### ISSUE TITLE
Exported machines use IDs for local transitions

### ISSUE THREAD

**Issue by tivac** [statelyai/editor-feedback#4]
Did a test export of the default starting machine, and I'm noticing that all the event targets are using fully-qualified IDs, even though the states they're transitioning to are right next to them. IDs are (as far as I knew) not recommended for transitions, and seem like they'd make the machine much more brittle in actual use?

![image](https://user-images.githubusercontent.com/49545/150839808-7ecda805-1df5-4355-85a4-26d7e0f2ca14.png)

```diff
{
  "id": "New Machine",
  "initial": "First State",
  "states": {
    "First State": {
      "on": {
        "Event": {
-          "target": "#New Machine.Second State"
+          "target": "Second State"
        }
      }
    },
    "Second State": {}
  }
}
```

**Comment by mattpocock** [comment]
Technically these are fine - but it's a sensible enhancement to shorten these in the exported output.

**Comment by tivac** [comment]
@mattpocock Was this fixed as part of this change?

https://stately.ai/blog/stately-changelog-1-snap-to-elements#improvements-to-vscode-output
