### ISSUE TITLE
license and business model?

### ISSUE THREAD

**Issue by mikestaub** [statelyai/editor-feedback#46]
Would it be possible to embed this editor in a product?

Are there plans to open-source the code?

**Comment by davidkpiano** [comment]
The editor is not embeddable yet, and there are no plans to make it open-source. The [Stately Visualizer](https://github.com/statelyai/xstate-viz) is open-source and MIT-licensed and embeddable, however.

**Comment by mikestaub** [comment]
Thanks for the quick response. I highly recommend talking to the founder of https://tooljet.com as I think their business model is the best. Our company would gladly pay for an enterprise license to self-host the app on-prem and I'm sure many others would.

**Comment by mattpocock** [comment]
Closing as the question was answered.
