### ISSUE TITLE
VS Code Extension is changing event properties

### ISSUE THREAD

**Issue by prestopasto** [statelyai/editor-feedback#49]
I can change an event to be Internal in the editor and the change is made correctly in the machine definition.  After saving the machine and going back to that event in the editor it reverts it to be External.

I have also tried changing the target to force it into being an internal transition, but the selecting the event in the editor also overwrites that.

There is an attached video showing this behavior.

https://user-images.githubusercontent.com/6289780/154999350-c7ee4581-ceea-4ac5-bf2e-0e7934348295.mov

**Comment by lewisl9029** [comment]
I'm seeing the same. This is a showstopper for me since turning internal transitions into external completely breaks my machine every time I open the editor.

**Comment by mattpocock** [comment]
This is now fixed in prod!

**Comment by prestopasto** [comment]
Woo! Thank you!
