### ISSUE TITLE
Simulator resets state on internal self-transition events

### ISSUE THREAD

**Issue by Tenga** [statelyai/editor-feedback#50]
When using internal self-transition events, the simulator resets the state that the event is attached to. This happens both in the VSC extension and browser.

This seems contrary to what the actual machine is doing when it's ran.

## Reproduction

1. [Open the following machine](https://stately.ai/registry/editor/ede0da9a-d2b4-4ac6-b470-1ffff136c41f)
1. Enter "Simulate" mode
1. Trigger `EVENT-1`, trigger `EVENT-2` then trigger `INTERNAL-1`
1. Observe that the `Substate-1` has reset, and `Substate-2` has not. In practice, both substates maintain their state.
1. Trigger `EVENT-1`, then trigger `INTERNAL-2`
1. Observe that the `Substate-2` has reset, and `Substate-1` has not. In practice, both substates maintain their state.
1. Trigger `EVENT-2`, then trigger `INTERNAL-ROOT`
1. Observe that the root state has reset. In practice, it maintains the state.

**Comment by Tenga** [comment]
After some messing around, the above repro might not actually be relevant here.

1) Editor itself, seemingly can't generate actual "internal self-transition events". `target` is always mandatory via the editor. When `target` is present, XState behaves as simulator does.

2) When manually editing the machine in the editor, and setting up an event like so:

    ```
    EVENT: {
        actions: "doSomething",
    },
    ```

    editor through VSC doesn't seem to read it in correctly and within it, this is represented as an external state with a target set to the origin state of the event.

    On write, this will be saved as:
    ```
    EVENT: {
        actions: "doSomething",
        target: "id-of-the-state-event-originates-from"
    },
    ```
    
    This unexpectedly changes the behavior of the machine.

2) Additionally, the `internal` flag is also not read in correctly and also gets removed on save. This also unexpectedly changes the behavior of the machine.


I can't tell if the simulator here is actually at fault, or if it's just the result of the mandatory target and misinterpretation of the event when reading the machine in.

**Comment by mattpocock** [comment]
This internal/target stuff is now fixed in prod. Thanks for the repro!
