### ISSUE TITLE
First guard in a guarded transition cannot go back to the previous state

### ISSUE THREAD

**Issue by blake-mealey** [statelyai/editor-feedback#72]
The first guard in a guarded transition cannot go back to the previous state. There is a workaround (invert the condition and use the else to go back) but this is confusing behaviour.

See video for repro steps:

https://user-images.githubusercontent.com/2432634/159756771-fab997ab-7c70-4f80-93c5-92f99f411026.mp4

**Comment by mattpocock** [comment]
Made a PR in core

**Comment by mattpocock** [comment]
Fixed in private repo, heading to prod soon
