### ISSUE TITLE
[Bug] Sim cannot trigger most non-standard events. 

### ISSUE THREAD

**Issue by aceslick911** [statelyai/editor-feedback#78]
I feel the sim could be a super-useful tool but I’ve never been able to trigger events beyond:
- normal event
- onDone event

Unable to trigger
- Always
- After
- Invoke (child states)
- Events that trigger a parallel transition
- Entry
- Exit

Is it possible to add a textbox to send a type to trigger in case the editor doesn’t know what is possible to trigger? (I assume full feature parity will be a few months away at least)

if you would like any specific debug information from me please let me know :)

**Comment by mattpocock** [comment]
Got any example machines which fail? We have some e2e tests in this area so I'm surprising that so many are failing.

**Comment by aceslick911** [comment]
Re-tested it today and the triggers seem to be working great - including all the examples above. Not sure if someone did some work or the fact that it's 7 days later (turn it on and off again) - but this is great!
