### ISSUE TITLE
[Bug] Selection popover isn't moving on changing zoom/scrolling with mousewheel

### ISSUE THREAD

**Issue by mikementor** [statelyai/editor-feedback#8]
Not sure, if that's an important thing,  it just caught my eye

https://user-images.githubusercontent.com/3846115/150845846-71f82130-845e-4807-844c-28a1f6e69695.mov

**Comment by Andarist** [comment]
This will get fixed soon - we already have a PR open for this

**Comment by mattpocock** [comment]
Fixed in most recent update
