### ISSUE TITLE
VS Code extension saving new invoke transitions from editor triggers auto layout of whole machine

### ISSUE THREAD

**Issue by void-mAlex** [statelyai/editor-feedback#85]
Prerequisites:
 - vscode extension 
 - create and save a new file with the following content
```javascript
import { createMachine } from 'xstate';

/** @xstate-layout N4IgpgJg5mDOIC5QDUwCcAuBLAxgQwBsBZPHACywDswA6AMSzVgwAIBlDPDMAYgFEAbmEoZEoAA4B7WFmyTKYkAA9EAWgBM6gCw0ArAA4AzOv3qA7IcMA2M1oAM+gDQgAnonW6AjDXN3L+gE4TMy99MwBfSOdKSQg4RVRMXEIScipaBiZWDi4wRSkZOQUkZTUPfRp9OwD9LS0rGoCtKq1nNwRPKwqgrQC7Lt0zEw8rKJBE7HxiUgpqGjwICABJSgFJfCL86VkseUUVBFVjCvUrdQCLT2stId02xEMDGgbDAKb6k2OxieTptLnqAB3FjMXIsTxbQq7YqgA7qOxmHyWByDPy6XQNdT3BAmbz9DEBQydMyEsyjcLOH5TVKzWhAkGcbgsdSQnZ7Epwuy6Z6vSw3fRdIwhbF1Ow0LlEgK6PpWOxaInfdCTFIzdKszYctSPdQ+M4XInXW7YqU0Hp9DGPLnEyKRIA */
export default createMachine({
	id: 'VerticalMachine',
	initial: 'First State',
	states: {
		'First State': {
			on: {
				Event: {
					target: 'addInvocation',
				},
			},
		},
		addInvocation: {
			description: 'can be any name\n- with this node selected ',
		},
		'new state 1': {
			description: 'drag success here',
		},
		'new state 2': {
			description: 'drag error here',
		},
	},
});
```

Starting from the above base open Visual editor
 - select the `addInvocation` node
 - using the side panel, the press `+` next to the invocations and type `test` (does not matter the name) in the src field and press save
 - using any of the three handles around the `addInvocation` node drag a link (_done_) to the `new state 1` node
 - re-select `addInvocation` node drag a link (_error_) to the `new state 2` node

at this point your happy with the machine and want to test it in the application so you save the vs code file
Expected:
layout is preserved as it was when the changes in the editor were complete

Actual:
autolayout is triggered re-flowing the whole machine

If the re-flow were to only affect the new nodes/states this would not be an issue.

Secondary usage pattern (this is how I actually use the editor) drag the _done_/_error_ to brand new nodes and move all four of the created elements until I am pleased with how they are laid out; saving ignores the locations of the places nodes/links

**Comment by void-mAlex** [comment]
expanding the scope to include adding an action to a guard of an `done` transition also triggers the auto layout

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1354/only-trigger-autolayout-explicitly

**Comment by mattpocock** [comment]
@void-mAlex Repeated this locally! Thanks for the detailed report. Definitely an error our side.

**Comment by mattpocock** [comment]
@void-mAlex Found the fix, PR'd to our private repo.

**Comment by void-mAlex** [comment]
this is great news, can I assume closing the issue means I can check the fix is live?

**Comment by mattpocock** [comment]
Not quite, give it a few more mins to release/deploy

**Comment by void-mAlex** [comment]
will do, excited to see the work to narrow down the cause and make the example as simple as possible paid off; feels really good to see things happen in response to feedback :)

**Comment by mattpocock** [comment]
Yeah it was a nasty edge case that we didn't catch in development. It was all about the moment you chose to save.

**Comment by mattpocock** [comment]
Releasing now, should be up in 10 mins.
