### ISSUE TITLE
[VS Code extension] Sign in to Stately action fails with error 

### ISSUE THREAD

**Issue by faustAbc** [statelyai/editor-feedback#88]
I tried to "Open Visual Editor", but it did nothing(no any warnings), so I checked if it logs in successfully. 

"XState: Sign in to Stately" fails with the following error:
```sh
[2022-04-20 23:10:38.897] [exthost] [error] ["Error: Input is not valid base64-encoded data."] stately-xstate.sign-in {"value":"statelyai.stately-vscode","_lower":"statelyai.stately-vscode"}
```

![image](https://user-images.githubusercontent.com/23014038/164306591-3154552b-408b-45ba-afe3-ba9cc228c2c8.png)

**Comment by faustAbc** [comment]
UPD: Some months ago I successfully opened editor as well as inspector in the extension

**Comment by faustAbc** [comment]
Found a solution!
Logged out, signed back in and it worked.

It might be connected with my old session idk.

**Comment by mattpocock** [comment]
Amazing! Closing
