### ISSUE TITLE
Should 'Fit to content' save current view for the machine?

### ISSUE THREAD

**Issue by mikementor** [statelyai/editor-feedback#9]
I've created a machine, somewhere not  in the exact center
clicked 'Fit to Content' - it works
then refreshed the page - now to get to the same view I'll need to click 'Fit to Content' again
https://user-images.githubusercontent.com/3846115/150847172-9b959362-cce2-4ecc-b58d-9c1c1db003d1.mov

**Comment by Andarist** [comment]
Thanks for bringing this up - we already have noted that down and fixing this has a high priority for us

**Comment by davidkpiano** [comment]
This is currently working in prod 👍
