### ISSUE TITLE
🤏 🔍  Pinch-to-Zoom, please

### ISSUE THREAD

**Issue by erikras** [statelyai/editor-feedback#99]
Every time I open the editor, I instinctively try to pinch zoom out, and every time I'm disappointed.

Thanks. 🙏

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1483/parallel-regions-should-not-be-markable-as-initial-states

**Comment by mattpocock** [comment]
Made a PR to private repo

**Comment by mattpocock** [comment]
Sent to prod
